### PR TITLE
Added missing parameter newDimension to ShipTeleportDataImpl constructor

### PR DESCRIPTION
**Pull request by xiewuzhiying**
Added missing parameter newDimension to ShipTeleportDataImpl constructor

### CODE REVIEW

**Comment by Rubydesic** [comment]
lgtm

**Comment by plasmadome** [comment]
So how do you do this?
How do you use the command?

**Comment by BlueStevie64** [comment]
> So how do you do this? How do you use the command?

I also have been trying to figure it out and I can't seem to use the teleport command past the coordinates. the [<euler-angles>] doesn't seem to be working as whatever I put there just brings up an error called "incomplete (expected 2 coordinates)"

**Comment by zyxkad** [comment]
nope it has nothing to deal with the teleport command, you need implement cross dimension teleport by yourself

**Pull request merged**
