### PR TITLE
Create 1_19_blocks

### PR DESCRIPTION
**Pull request by Weromano**

### CODE REVIEW

**Comment by ewoudje** [comment]
@ThePlasticPotato you check this since its create 🔫

**Comment by walksanatora** [comment]
> @ThePlasticPotato you check this since its create 🔫

I am going to execute you... and I dont even participate much...

**Comment by PriestOfFerns** [comment]
> @ThePlasticPotato you check this since its create 🔫

it has nothing to do with create :suspect:

**Comment by ThePlasticPotato** [comment]
This isn’t create related you numbskull it’s just creating a file

**Comment by ThePlasticPotato** [comment]
Anyways these values seem fair

**Comment by ewoudje** [comment]
Nono look in the title its "Create"
Has to be obv create right?

**Comment by PriestOfFerns** [comment]
> Nono look in the title its "Create"
> Has to be obv create right?

mf replied a week later

**Comment by ewoudje** [comment]
I feel like mud should be heavier or is that just me? 1000kg is just water, mud is only 400kg more? Is this how mud works?

**Pull request merged**
