### PR TITLE
fix crash with Sodium and Litematica

### PR DESCRIPTION
**Pull request by pama1234**
fix https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/818

### CODE REVIEW

**Comment by Hex4dec** [comment]
You should probably do the client check way earlier, maybe at the start of each render function. And why are you doing the client check through dispatcher? Just do level.isClient?

**Review by ewoudje — APPROVED** [review]
LGTM

**Comment by dti131** [comment]
image
Fix #819 does fix the crashing issue, but it adds another issue (much less severe) where blocks that have animations or other entities (such as the blaze burner and conveyor belt) will be rendered near the player. This can be "fixed" by moving to an area without those blocks, though.

**Comment by chen-0917** [comment]
> image修复 #819 确实修复了崩溃问题，但它增加了另一个问题（不那么严重），即具有动画或其他实体（例如烈焰燃烧器和传送带）的块将在玩家附近渲染。不过，这可以通过移动到没有这些方块的区域来“修复”。
Can you send me the built file, I'm a novice, and I tried for a day but I kept getting an error

**Comment by Ozzer0** [comment]
> image Fix #819 does fix the crashing issue, but it adds another issue (much less severe) where blocks that have animations or other entities (such as the blaze burner and conveyor belt) will be rendered near the player. This can be "fixed" by moving to an area without those blocks, though.

Having a similar issue with vanilla block entities.

**Pull request merged**
