### PR TITLE
Added Create Seat entity into VS_Entities

### PR DESCRIPTION
**Pull request by FluffyJenkins**
Hate it when ships don't take a seat when you went through the effort of offering!

### CODE REVIEW

**Comment by walksanatora** [comment]
I thought seats were blocks though
Then again it makes sense that they used a entity
Create is spaghet rough as is

**Comment by ThePlasticPotato** [comment]
you cant sit on a block, they have to use entities because mojank

**Comment by ThePlasticPotato** [comment]
yes I know that, i meant you cant mount a block directly so they use an entity

**Comment by ThePlasticPotato** [comment]
ahh sorry i didnt mean to come off as rude dfgsdfg

**Comment by ThePlasticPotato** [comment]
anyways this is grossly misusing github comments :clueless:

**Pull request merged**
