### PR TITLE
1.18.x tis-3d rendering+infared fixes

### PR DESCRIPTION
**Pull request by walksanatora**
This fixes rendering issues on TIS-3D
meaning that TIS-3D can actually be used on ValkrienSkies ships now (AFAIK)

### CODE REVIEW

**Comment by Rubydesic** [comment]
Have you tested this compatibility outside of your dev environment? (by building the mod as a JAR and using it normally with TIS-3D)

**Comment by Rubydesic** [comment]
I see some suspicious remap=false

**Comment by walksanatora** [comment]
I was told to remap=false when targeting non-mc classes

**Comment by Rubydesic** [comment]
Did you test it?

**Comment by walksanatora** [comment]
okay after a quick test
rendering: fixed
infared: not fixed (does not work ship within ship, ship <-> world and ship <-> other ship are ValkComp things)
i need to figure out why infared is like this, but this makes TIS-3d atleast *usable* on ships (although not 100%)

**Comment by walksanatora** [comment]
so inorder to fix the Infared i gotta fix a raycast
do you know if VSGameUtilsKt has a function to replace the raycast

**Comment by walksanatora** [comment]
infared still broken, when i get home gonna run under a debugger (darn forgeGradle runClient not working with --offline)

**Comment by walksanatora** [comment]
@Rubydesic Finally works 
i tested and it works
the only reason why infared packets can miss is because you were going too fast or rotating too quickly (since they are pretty slow entities) but otherwise it works perfectly (even on rotated ships)

**Pull request merged**
