### PR TITLE
Fix TFC compatibility issue

### PR DESCRIPTION
**Pull request by Dokueki**
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/832

### CODE REVIEW

**Comment by MayTheCutie** [comment]
This isn't fixed. Y'all might need to change where the mixins of world creation are, since you're referencing vanilla chunkgen. Would y'all be able to figure out a different way for this since there's other mods that have chunkgen?

**Comment by Rubydesic** [comment]
> This isn't fixed. Y'all might need to change where the mixins of world creation are, since you're referencing vanilla chunkgen. Would y'all be able to figure out a different way for this since there's other mods that have chunkgen?
> 
> It'd help the mod more if you made this a tad more compatible to other mods too, not just tfc

Definitely! I'm more than happy to review a PR if you have a better way of managing shipyard chunk generation in mind. Merry Christmas!

**Comment by IslamSir** [comment]
I think will be better to change the TFC chunkgen, if you say so

**Comment by ISGRain** [comment]
seams relatively compatible in 1.18 but not in 1.20, not sure if it just wasn't implemented in both or if tfc changed its gen since figured it was worth bringing up though

**Comment by PriestOfFerns** [comment]
@ISGRain  Did you test using the github versions of VS2?

**Pull request merged**
